Lower the minimum-required version of zendframework/zend-dom to 2.2.5.
Versions prior to 2.2.5 would cause the tests for this package to emit errors like the following:

1) Tests\MarkupAssertionsTraitTest::testAssertContainsSelector with data set "Tag with href attribute" ('a[href="https://example.com"]')
ErrorException: DOMXPath::query(): Invalid predicate

/phpunit-markup-assertions/vendor/zendframework/zend-dom/src/Query.php:317
/phpunit-markup-assertions/vendor/zendframework/zend-dom/src/Query.php:269
/phpunit-markup-assertions/vendor/zendframework/zend-dom/src/Query.php:214
/phpunit-markup-assertions/src/MarkupAssertionsTrait.php:106
/phpunit-markup-assertions/src/MarkupAssertionsTrait.php:26
/phpunit-markup-assertions/tests/MarkupAssertionsTraitTest.php:31

Refs #9.